[package]
name = "todo-rs"
version = "0.1.0"
authors = ["iddar <iddar@dbug.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "0.7.0"
gtk = { version = "0.3.0", features = ["v3_22"] }
